DataRefReplacer fixes
matecat/xliff-parser pull request #16
Opened 2021-06-25 15:20 UTC by mauretto78

2021-06-25 16:48 UTC, Ostico requested changes

2021-06-25 16:48 UTC, Ostico commented on src/XliffUtils/DataRefReplacer.php
> +    private function dsadas( $node, &$dataRefEndMap)
Oooops xD

2021-06-28 07:38 UTC, mauretto78 commented on src/XliffUtils/DataRefReplacer.php
> +    private function dsadas( $node, &$dataRefEndMap)
@Ostico typo fixed :)

2021-06-28 10:36 UTC, FrancescoE approved these changes

2021-06-28 13:02 UTC, merged